//! Compact-wire grammar: production-reader oracle plus generated GBNF.
//!
//! The GBNF is generated from the CoLisp and Co-Forth reader lexicons. It is
//! a complete-response recognizer, not a proof of types, vocabulary, stack
//! effects, capabilities, or host-effect safety. Provider-native tool calls
//! remain a separate channel.

use crate::gbnf;
use finch_coforth::{forth_lexicon, read_forth_source};
use finch_colisp::{lisp_lexicon, parse_str};
use finch_vm_core::ProgramLanguage;
use std::fmt::Write as _;
use std::sync::OnceLock;

/// Version of the published compact-wire GBNF.
pub const WIRE_GRAMMAR_VERSION: u32 = 1;

/// Path of the committed grammar artifact, relative to the repository root.
pub const WIRE_GRAMMAR_ARTIFACT: &str = "vocabulary/language/wire.gbnf";

#[cfg(test)]
const PUBLISHED_WIRE_GBNF: &str = include_str!("../../../vocabulary/language/wire.gbnf");

/// Why a compact-wire submission was rejected before compilation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireReject {
    /// Stable diagnostic code such as `E-WIRE-002` or `E-READ-008`.
    pub code: String,
    /// Human-readable reason. Not a semantic safety proof.
    pub message: String,
}

impl std::fmt::Display for WireReject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}

/// Production-reader oracle for a complete compact-wire `ProgramSubmission`.
///
/// Dispatch uses [`ProgramLanguage::infer_wire_source`]. Lisp uses the CoLisp
/// reader; Co-Forth uses the Co-Forth tokenizer plus syntactic completeness.
/// Unknown words are accepted.
pub fn accepts_wire_source(source: &str) -> Result<ProgramLanguage, WireReject> {
    let language = ProgramLanguage::infer_wire_source(source).map_err(dispatch_reject)?;
    match language {
        ProgramLanguage::Lisp => {
            parse_str(source).map_err(|error| WireReject {
                code: "E-READ-LISP".to_string(),
                message: error.to_string(),
            })?;
        }
        ProgramLanguage::Forth => {
            if let Err(errors) = read_forth_source("wire.forth", source) {
                let code = errors
                    .first()
                    .map(|error| error.code.clone())
                    .unwrap_or_else(|| "E-READ-FORTH".to_string());
                let message = errors
                    .iter()
                    .map(|error| error.message.as_str())
                    .collect::<Vec<_>>()
                    .join("; ");
                return Err(WireReject { code, message });
            }
        }
    }
    Ok(language)
}

/// True when the published GBNF accepts `source` as a complete submission.
pub fn accepts_published_grammar(source: &str) -> bool {
    gbnf::matches(published_grammar(), source)
}

/// Render the canonical compact-wire GBNF from production reader lexicons.
pub fn render_wire_gbnf() -> String {
    let lisp = lisp_lexicon();
    let forth = forth_lexicon();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Finch compact-wire ProgramSubmission grammar v{WIRE_GRAMMAR_VERSION}"
    );
    let _ = writeln!(
        out,
        "# Generated from production Lisp/Co-Forth reader lexicons by finch_language::render_wire_gbnf."
    );
    let _ = writeln!(
        out,
        "# Complete-response recognizer only. Not a proof of types, capabilities, or host-effect safety."
    );
    let _ = writeln!(
        out,
        "# Markdown fences and empty submissions are rejected. Provider-native tool calls are a separate channel."
    );
    let _ = writeln!(
        out,
        "# Do not edit this file by hand. Update the generator and regenerate {WIRE_GRAMMAR_ARTIFACT}."
    );
    let _ = writeln!(out);

    rule(
        &mut out,
        "root",
        "lead ( lisp-program | forth-program ) lead",
    );
    rule(&mut out, "lead", "unicode-ws*");
    rule(&mut out, "unicode-ws", &unicode_whitespace_class());

    rule(
        &mut out,
        "lisp-program",
        "lisp-list lisp-gap* ( lisp-form lisp-gap* )*",
    );
    rule(
        &mut out,
        "lisp-gap",
        "unicode-ws | lisp-line-comment | lisp-block-comment",
    );
    rule(
        &mut out,
        "lisp-line-comment",
        &format!("{} [^\\n]*", gbnf_literal(&lisp.line_comment.to_string())),
    );
    rule(
        &mut out,
        "lisp-block-comment",
        &format!(
            "{} lisp-block-body {}",
            gbnf_literal(lisp.block_comment_open),
            gbnf_literal(lisp.block_comment_close)
        ),
    );
    rule(&mut out, "lisp-block-body", "( [^|] | \"|\" [^#] )*");
    rule(
        &mut out,
        "lisp-form",
        "lisp-splice | lisp-unquote | lisp-quote | lisp-quasiquote | lisp-list | lisp-string | lisp-math | lisp-compact | lisp-brace | lisp-array | lisp-atom",
    );
    rule(
        &mut out,
        "lisp-splice",
        &format!("{} lisp-gap* lisp-form", gbnf_literal(lisp.unquote_splice)),
    );
    rule(
        &mut out,
        "lisp-unquote",
        &format!(
            "{} lisp-gap* lisp-form",
            gbnf_literal(&lisp.unquote.to_string())
        ),
    );
    rule(
        &mut out,
        "lisp-quote",
        &format!(
            "{} lisp-gap* lisp-form",
            gbnf_literal(&lisp.quote.to_string())
        ),
    );
    rule(
        &mut out,
        "lisp-quasiquote",
        &format!(
            "{} lisp-gap* lisp-form",
            gbnf_literal(&lisp.quasiquote.to_string())
        ),
    );
    rule(
        &mut out,
        "lisp-list",
        &format!(
            "{} lisp-gap* ( lisp-form lisp-gap* )* {}",
            gbnf_literal(&lisp.list_open.to_string()),
            gbnf_literal(&lisp.list_close.to_string())
        ),
    );
    rule(
        &mut out,
        "lisp-string",
        &format!(
            "{} lisp-str-char* {}",
            gbnf_literal(&lisp.string_delimiter.to_string()),
            gbnf_literal(&lisp.string_delimiter.to_string())
        ),
    );
    rule(&mut out, "lisp-str-char", r#" "\\" . | [^"\\] "#);
    rule(
        &mut out,
        "lisp-math",
        &format!(
            "{} math-ws* math-bit ( math-ws* math-bit )* math-ws* {}",
            gbnf_literal(&lisp.math_delimiter.to_string()),
            gbnf_literal(&lisp.math_delimiter.to_string())
        ),
    );
    rule(&mut out, "math-ws", "unicode-ws");
    rule(
        &mut out,
        "math-bit",
        r#"[+\-*/^()] | math-num | math-ident"#,
    );
    rule(&mut out, "math-num", r#"[0-9]+ ( "." [0-9]* )?"#);
    rule(&mut out, "math-ident", r#"[a-zA-Z_] [a-zA-Z0-9_]*"#);
    rule(
        &mut out,
        "lisp-compact",
        &compact_prefix_alts(lisp.compact_type_prefixes),
    );
    rule(&mut out, "compact-body", "compact-chunk*");
    rule(
        &mut out,
        "compact-chunk",
        r#"compact-plain | "{" compact-body "}""#,
    );
    rule(&mut out, "compact-plain", r#"[^ \t\n\r\x0b\x0c"{}]+"#);
    rule(&mut out, "lisp-brace", "json-object | lisp-record");
    rule(
        &mut out,
        "lisp-record",
        &format!(
            "{} lisp-gap* ( \":\" lisp-atom lisp-gap+ lisp-form lisp-gap* )* {}",
            gbnf_literal(&lisp.record_open.to_string()),
            gbnf_literal(&lisp.record_close.to_string())
        ),
    );
    rule(&mut out, "lisp-array", "json-array");
    rule(&mut out, "lisp-atom", "lisp-atom-start lisp-atom-piece*");
    rule(&mut out, "lisp-atom-start", &lisp_atom_start_class());
    rule(&mut out, "lisp-atom-piece", "lisp-plain | lisp-angles");
    rule(&mut out, "lisp-plain", &lisp_plain_class());
    rule(&mut out, "lisp-angles", "\"<\" lisp-angle-body \">\"");
    rule(
        &mut out,
        "lisp-angle-body",
        "( lisp-plain | \",\" | lisp-angles )*",
    );

    rule(&mut out, "json-ws", "unicode-ws");
    rule(&mut out, "json-object", "\"{\" json-ws* json-object-body");
    rule(
        &mut out,
        "json-object-body",
        "\"}\" | json-member ( json-ws* \",\" json-ws* json-member )* json-ws* \"}\"",
    );
    rule(
        &mut out,
        "json-member",
        "json-string json-ws* \":\" json-ws* json-value",
    );
    rule(&mut out, "json-array", "\"[\" json-ws* json-array-body");
    rule(
        &mut out,
        "json-array-body",
        "\"]\" | json-value ( json-ws* \",\" json-ws* json-value )* json-ws* \"]\"",
    );
    rule(
        &mut out,
        "json-value",
        "json-object | json-array | json-string | json-number | \"true\" | \"false\" | \"null\"",
    );
    rule(&mut out, "json-string", r#" "\"" json-str-char* "\"" "#);
    rule(
        &mut out,
        "json-str-char",
        r#" json-escape | json-unescaped "#,
    );
    rule(
        &mut out,
        "json-escape",
        r#" "\\" ( ["\\/bfnrt] | "u" json-hex json-hex json-hex json-hex ) "#,
    );
    rule(&mut out, "json-hex", r#"[0-9a-fA-F]"#);
    rule(&mut out, "json-unescaped", r#"[^"\\\x00-\x1f]"#);
    rule(
        &mut out,
        "json-number",
        r#" "-"? json-int json-frac? json-exp? "#,
    );
    rule(&mut out, "json-int", r#" "0" | [1-9] [0-9]* "#);
    rule(&mut out, "json-frac", r#" "." [0-9]+ "#);
    rule(&mut out, "json-exp", r#" [eE] ( "+" | "-" )? [0-9]+ "#);

    rule(&mut out, "ascii-ws", r#"[ \t\n\r\x0b\x0c]"#);
    rule(&mut out, "forth-ws", "ascii-ws");
    rule(
        &mut out,
        "forth-comment",
        &format!("{} [^\\n]*", gbnf_literal(&forth.line_comment.to_string())),
    );
    rule(
        &mut out,
        "forth-gap",
        &format!(
            "forth-ws | {} | forth-comment",
            gbnf_literal(&forth.comma_separator.to_string())
        ),
    );
    rule(&mut out, "forth-program", "forth-ws* forth-nonempty");
    rule(
        &mut out,
        "forth-nonempty",
        "forth-comment forth-more | forth-first forth-more",
    );
    rule(
        &mut out,
        "forth-more",
        "forth-gap* ( forth-item forth-gap* )*",
    );
    rule(
        &mut out,
        "forth-first",
        "forth-raw | forth-string | forth-def | forth-compact | forth-collection | forth-type | forth-bracket | forth-json | forth-record | forth-first-word",
    );
    rule(
        &mut out,
        "forth-item",
        "forth-raw | forth-string | forth-def | forth-compact | forth-collection | forth-type | forth-bracket | forth-json | forth-record | forth-word",
    );

    let raw_openers: Vec<_> = forth
        .string_openers
        .iter()
        .filter(|opener| opener.raw)
        .map(|opener| {
            format!(
                "{} raw-body {}",
                gbnf_literal(opener.spelling),
                gbnf_literal(forth.raw_string_close)
            )
        })
        .collect();
    rule(&mut out, "forth-raw", &raw_openers.join(" | "));
    rule(
        &mut out,
        "raw-body",
        r#"( [^"] | "\"" [^"] | "\"\"" [^"] )*"#,
    );

    let escaped: Vec<_> = forth
        .string_openers
        .iter()
        .filter(|opener| !opener.raw)
        .map(|opener| {
            if opener.skip_one_ascii_ws {
                format!("{} ascii-ws? esc-body", gbnf_literal(opener.spelling))
            } else {
                format!("{} esc-body", gbnf_literal(opener.spelling))
            }
        })
        .collect();
    rule(&mut out, "forth-string", &escaped.join(" | "));
    rule(&mut out, "esc-body", r#" esc-char* "\"" "#);
    rule(&mut out, "esc-char", r#" "\\" . | [^"\\] "#);

    rule(
        &mut out,
        "forth-def",
        &format!(
            "{} forth-gap+ forth-word forth-gap+ {} forth-sig-body {} forth-def-body {}",
            gbnf_literal(forth.definition_start),
            gbnf_literal(forth.signature_open),
            gbnf_literal(forth.signature_close),
            gbnf_literal(forth.definition_end)
        ),
    );
    rule(
        &mut out,
        "forth-sig-body",
        "( forth-gap | forth-string | forth-raw | forth-sig-word | forth-compact | forth-type )*",
    );
    rule(&mut out, "forth-sig-word", &forth_sig_word_class());
    rule(
        &mut out,
        "forth-def-body",
        "( forth-gap+ forth-body-item )* forth-gap*",
    );
    rule(
        &mut out,
        "forth-body-item",
        "forth-raw | forth-string | forth-compact | forth-collection | forth-type | forth-bracket | forth-json | forth-record | forth-body-word",
    );

    rule(
        &mut out,
        "forth-compact",
        &compact_prefix_alts(forth.compact_type_prefixes),
    );

    let collection_alts: Vec<_> = forth
        .collection_openers
        .iter()
        .chain(forth.collection_closers.iter())
        .map(|spelling| gbnf_literal(spelling))
        .collect();
    rule(&mut out, "forth-collection", &collection_alts.join(" | "));

    let type_alts: Vec<_> = forth
        .parameterized_type_prefixes
        .iter()
        .map(|prefix| format!("{} [^ \\t\\n\\r>]* \">\"", gbnf_literal(prefix)))
        .collect();
    rule(&mut out, "forth-type", &type_alts.join(" | "));

    rule(&mut out, "forth-bracket", "forth-quote | forth-list");
    rule(
        &mut out,
        "forth-quote",
        &format!(
            "{} forth-gap* {} forth-gap* forth-qhead {} forth-quote-body {}",
            gbnf_literal(&forth.list_open.to_string()),
            gbnf_literal(forth.quotation_arrow),
            gbnf_literal(forth.quotation_pipe),
            gbnf_literal(&forth.list_close.to_string())
        ),
    );
    rule(&mut out, "forth-qhead", "( forth-word forth-gap* )*");
    rule(
        &mut out,
        "forth-quote-body",
        "( forth-gap | forth-body-item )*",
    );
    rule(
        &mut out,
        "forth-list",
        &format!(
            "{} forth-gap* ( forth-body-item forth-gap* )* {}",
            gbnf_literal(&forth.list_open.to_string()),
            gbnf_literal(&forth.list_close.to_string())
        ),
    );
    rule(&mut out, "forth-json", "json-object");
    rule(
        &mut out,
        "forth-record",
        &format!(
            "{} forth-gap* ( forth-word forth-gap+ forth-body-item forth-gap* )* {}",
            gbnf_literal(&forth.record_open.to_string()),
            gbnf_literal(&forth.record_close.to_string())
        ),
    );
    rule(
        &mut out,
        "forth-word",
        "\":\" forth-word-char+ | forth-plain-start forth-word-char*",
    );
    rule(
        &mut out,
        "forth-body-word",
        "\":\" forth-body-word-char+ | forth-body-plain-start forth-body-word-char*",
    );
    rule(
        &mut out,
        "forth-first-word",
        "\":\" forth-word-char+ | forth-first-start forth-word-char*",
    );
    rule(&mut out, "forth-plain-start", &forth_plain_start_class());
    rule(
        &mut out,
        "forth-body-plain-start",
        &forth_body_plain_start_class(),
    );
    rule(&mut out, "forth-word-char", &forth_word_class());
    rule(&mut out, "forth-body-word-char", &forth_body_word_class());
    rule(
        &mut out,
        "forth-first-start",
        &format!(
            "{} | \"`\" \"`\"? {}",
            forth_first_start_class(),
            forth_first_start_class()
        ),
    );

    out
}

fn published_grammar() -> &'static gbnf::Grammar {
    static GRAMMAR: OnceLock<gbnf::Grammar> = OnceLock::new();
    GRAMMAR.get_or_init(|| {
        gbnf::parse(&render_wire_gbnf()).expect("generated Finch wire GBNF must parse")
    })
}

fn dispatch_reject(error: impl std::fmt::Display) -> WireReject {
    let message = error.to_string();
    let code = message
        .split_once(':')
        .map(|(code, _)| code.trim().to_string())
        .unwrap_or_else(|| "E-WIRE".to_string());
    WireReject { code, message }
}

fn rule(out: &mut String, name: &str, body: &str) {
    let _ = writeln!(out, "{name} ::= {body}");
}

fn gbnf_literal(text: &str) -> String {
    let mut out = String::from("\"");
    for ch in text.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn compact_prefix_alts(prefixes: &[&str]) -> String {
    prefixes
        .iter()
        .map(|prefix| format!("{} compact-body \"}}\"", gbnf_literal(prefix)))
        .collect::<Vec<_>>()
        .join(" | ")
}

fn push_class_char(out: &mut String, ch: char) {
    match ch {
        '\\' | ']' | '-' | '^' => {
            out.push('\\');
            out.push(ch);
        }
        '\n' => out.push_str("\\n"),
        '\r' => out.push_str("\\r"),
        '\t' => out.push_str("\\t"),
        c if (c as u32) < 0x20 || c == '\u{7f}' => {
            let _ = write!(out, "\\x{:02x}", c as u32);
        }
        c => out.push(c),
    }
}

fn unicode_whitespace_class() -> String {
    let mut out = String::from("[");
    for ch in (0..=0x10FFFF)
        .filter_map(char::from_u32)
        .filter(|ch| ch.is_whitespace())
    {
        push_class_char(&mut out, ch);
    }
    out.push(']');
    out
}

fn lisp_plain_class() -> String {
    lisp_atom_class(false)
}

fn lisp_atom_start_class() -> String {
    lisp_atom_class(true)
}

fn lisp_atom_class(exclude_math_delimiter: bool) -> String {
    // Complement of whitespace and the reader atom delimiters plus type-arg brackets.
    // A form starting with `$` is math, not an atom: excluding the delimiter from
    // atom-start stops `$@@@$` from falling through after lisp-math fails.
    let mut forbidden = String::from("[^");
    for ch in (0..=0x10FFFF)
        .filter_map(char::from_u32)
        .filter(|ch| ch.is_whitespace())
    {
        push_class_char(&mut forbidden, ch);
    }
    for ch in "(){}\"';`,<>".chars() {
        push_class_char(&mut forbidden, ch);
    }
    if exclude_math_delimiter {
        push_class_char(&mut forbidden, lisp_lexicon().math_delimiter);
    }
    forbidden.push(']');
    forbidden
}

fn forth_word_class() -> String {
    negated_class(&[
        b'\t', b'\n', 0x0b, 0x0c, b'\r', b' ', b',', b'"', b'[', b']', b'}',
    ])
}

fn forth_body_word_class() -> String {
    negated_class(&[
        b'\t', b'\n', 0x0b, 0x0c, b'\r', b' ', b',', b'"', b'[', b']', b'}', b';',
    ])
}

fn forth_sig_word_class() -> String {
    negated_class(&[
        b'\t', b'\n', 0x0b, 0x0c, b'\r', b' ', b',', b'"', b'(', b')', b'[', b']', b'}',
    ])
}

fn forth_plain_start_class() -> String {
    negated_class(&[
        b':', b'\t', b'\n', 0x0b, 0x0c, b'\r', b' ', b',', b'"', b'[', b']', b'}',
    ])
}

fn forth_body_plain_start_class() -> String {
    negated_class(&[
        b':', b'\t', b'\n', 0x0b, 0x0c, b'\r', b' ', b',', b'"', b'[', b']', b'}', b';',
    ])
}

fn forth_first_start_class() -> String {
    negated_class(&[
        b'`', b'(', b':', b'\t', b'\n', 0x0b, 0x0c, b'\r', b' ', b',', b'"', b'[', b']', b'}',
    ])
}

fn negated_class(bytes: &[u8]) -> String {
    let mut out = String::from("[^");
    for byte in bytes {
        push_class_char(&mut out, *byte as char);
    }
    out.push(']');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Fixture {
        source: &'static str,
        accept: bool,
        kind: &'static str,
    }

    fn fixtures() -> Vec<Fixture> {
        vec![
            Fixture {
                source: "(say \"Hello\")",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "  (say \"Hello\")",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(+ 1 2)",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(begin (say \"a\") (say \"b\"))",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(say \"a\\nb\")",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(say #| c |# \"hi\")",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(let ((x 1)) x)",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(foo $1+2$)",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(foo { :name \"Ada\" })",
                accept: true,
                kind: "lisp",
            },
            Fixture {
                source: "(record{name:string})",
                accept: true,
                kind: "lisp-compact",
            },
            Fixture {
                source: "({ :ty record{name:string} })",
                accept: true,
                kind: "lisp-compact",
            },
            Fixture {
                source: "(variant{none|some(int)|metadata(record{name:string})})",
                accept: true,
                kind: "lisp-compact",
            },
            Fixture {
                source: "(foo $@@@$)",
                accept: false,
                kind: "lisp-math",
            },
            Fixture {
                source: "(foo { \"a\": 01 })",
                accept: false,
                kind: "json-number",
            },
            Fixture {
                source: "(foo { \"a\": \"\\q\" })",
                accept: false,
                kind: "json-string",
            },
            Fixture {
                source: "(foo { \"a\": 1e2 })",
                accept: true,
                kind: "json-number",
            },
            Fixture {
                source: "{\"a\": 1e2}",
                accept: true,
                kind: "forth-json",
            },
            Fixture {
                source: "\"Hello\" say",
                accept: true,
                kind: "forth",
            },
            Fixture {
                source: "s\"Hello\" say",
                accept: true,
                kind: "forth",
            },
            Fixture {
                source: ".\"Hello\"",
                accept: true,
                kind: "forth",
            },
            Fixture {
                source: "\"don't\" say",
                accept: true,
                kind: "contraction",
            },
            Fixture {
                source: "\"\"\"don't panic\"\"\" say",
                accept: true,
                kind: "raw-string",
            },
            Fixture {
                source: "s\"\"\"raw \"quotes\" and don't\"\"\" say",
                accept: true,
                kind: "raw-string",
            },
            Fixture {
                source: "1 2 +",
                accept: true,
                kind: "forth",
            },
            Fixture {
                source: ": square ( S int -- S int ! pure ) dup * ; 5 square",
                accept: true,
                kind: "forth-def",
            },
            Fixture {
                source: "[ -- int ! pure | 42 ]",
                accept: true,
                kind: "forth-quote",
            },
            Fixture {
                source: "true if 1 else 2 then",
                accept: true,
                kind: "forth",
            },
            Fixture {
                source: "\"hi\" say \\ trailing comment",
                accept: true,
                kind: "forth-comment",
            },
            Fixture {
                source: "Sure I'll help",
                accept: true,
                kind: "prose-as-tokens",
            },
            Fixture {
                source: "don't!",
                accept: true,
                kind: "contraction",
            },
            Fixture {
                source: "",
                accept: false,
                kind: "empty",
            },
            Fixture {
                source: "   \n\t",
                accept: false,
                kind: "empty",
            },
            Fixture {
                source: "```forth\n\"hi\" say\n```",
                accept: false,
                kind: "fence",
            },
            Fixture {
                source: "```lisp\n(say \"hi\")\n```",
                accept: false,
                kind: "fence",
            },
            Fixture {
                source: "  ```\n1\n```",
                accept: false,
                kind: "fence",
            },
            Fixture {
                source: "(",
                accept: false,
                kind: "lisp-incomplete",
            },
            Fixture {
                source: "(say \"unterminated",
                accept: false,
                kind: "lisp-incomplete",
            },
            Fixture {
                source: "())",
                accept: false,
                kind: "lisp-unbalanced",
            },
            Fixture {
                source: "\"unterminated",
                accept: false,
                kind: "forth-incomplete",
            },
            Fixture {
                source: "s\"\"\"unterminated",
                accept: false,
                kind: "raw-string",
            },
            Fixture {
                source: ": square ( S int -- S int ! pure ) dup *",
                accept: false,
                kind: "forth-def",
            },
            Fixture {
                source: "[ -- int | 42",
                accept: false,
                kind: "forth-quote",
            },
            Fixture {
                source: "[ 1 2",
                accept: false,
                kind: "forth-list",
            },
        ]
    }

    #[test]
    fn test_wire_grammar_accepts_iff_production_reader() {
        let mut mismatches = Vec::new();
        for fixture in fixtures() {
            let reader = accepts_wire_source(fixture.source).is_ok();
            let grammar = accepts_published_grammar(fixture.source);
            if reader != grammar || reader != fixture.accept {
                mismatches.push(format!(
                    "kind={kind} accept={want} reader={reader} grammar={grammar} source={source:?}",
                    kind = fixture.kind,
                    want = fixture.accept,
                    source = fixture.source
                ));
            }
        }
        assert!(
            mismatches.is_empty(),
            "published GBNF must accept iff the production reader accepts (and match the fixture oracle):\n{}",
            mismatches.join("\n")
        );
    }

    #[test]
    fn test_published_wire_gbnf_matches_generator() {
        let generated = render_wire_gbnf();
        if generated != PUBLISHED_WIRE_GBNF {
            let _ = std::fs::write("/tmp/finch-wire.gbnf", &generated);
        }
        assert_eq!(
            generated, PUBLISHED_WIRE_GBNF,
            "vocabulary/language/wire.gbnf drifted from finch_language::render_wire_gbnf(); copy /tmp/finch-wire.gbnf if the generator change is intended"
        );
    }

    #[test]
    fn test_generated_gbnf_embeds_reader_lexicon_markers() {
        let gbnf = render_wire_gbnf();
        let lisp = lisp_lexicon();
        let forth = forth_lexicon();
        for marker in [
            gbnf_literal(&lisp.line_comment.to_string()),
            gbnf_literal(lisp.block_comment_open),
            gbnf_literal(&lisp.list_open.to_string()),
            gbnf_literal(&forth.line_comment.to_string()),
            gbnf_literal(forth.raw_string_close),
            gbnf_literal(forth.definition_start),
        ] {
            assert!(
                gbnf.contains(&marker),
                "generated GBNF must contain reader lexicon marker {marker}: grammar={gbnf}"
            );
        }
        for opener in forth.string_openers {
            let literal = gbnf_literal(opener.spelling);
            assert!(
                gbnf.contains(&literal),
                "generated GBNF must contain Co-Forth string opener {literal}"
            );
        }
        for prefix in lisp.compact_type_prefixes {
            let literal = gbnf_literal(prefix);
            assert!(
                gbnf.contains(&literal),
                "generated GBNF must contain CoLisp compact type prefix {literal} so record{{…}}/variant{{…}} stay single atoms"
            );
        }
        for prefix in forth.compact_type_prefixes {
            let literal = gbnf_literal(prefix);
            assert!(
                gbnf.contains(&literal),
                "generated GBNF must contain Co-Forth compact type prefix {literal}"
            );
        }
    }

    #[test]
    fn test_wire_grammar_known_overapprox() {
        // Token-valid math that is not a complete expression still matches the
        // CFG. These holes must not widen: reader rejects, grammar accepts.
        // Closing a hole means moving the fixture into the iff corpus.
        let holes = [
            (
                "(foo $+$)",
                "operator-only math is not a parseable expression",
            ),
            ("(foo $(1$)", "math with an unclosed parenthesis"),
        ];
        let mut failures = Vec::new();
        for (source, why) in holes {
            let reader = accepts_wire_source(source).is_ok();
            let grammar = accepts_published_grammar(source);
            if reader || !grammar {
                failures.push(format!(
                    "known CFG overapprox drifted ({why}): reader_accepts={reader} grammar_accepts={grammar} source={source:?}"
                ));
            }
        }
        assert!(
            failures.is_empty(),
            "documented GBNF overapprox holes must stay reader-reject/grammar-accept:\n{}",
            failures.join("\n")
        );
    }

    #[test]
    fn test_wire_grammar_does_not_claim_semantic_safety() {
        let source = "Sure I'll help";
        assert!(
            accepts_wire_source(source).is_ok(),
            "unknown-word prose is complete Co-Forth syntax; vocabulary remains a verifier concern: {source:?}"
        );
        assert!(
            accepts_published_grammar(source),
            "the CFG must not be presented as semantic safety: {source:?}"
        );
    }

    #[test]
    fn test_generated_gbnf_parses() {
        gbnf::parse(&render_wire_gbnf()).expect("generated wire GBNF must be valid GBNF");
    }
}
