#!/usr/bin/env python3
"""Regression tests for the tracked repository hygiene guard."""

from __future__ import annotations

import hashlib
import struct
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CHECKER = ROOT / "scripts/check_repository_hygiene.py"
HEADER = (
    "path\tsha256\tsize\tplatform\tlicense\tprovenance_document\t"
    "generation_reason\n"
)


class HygieneRepository:
    def __init__(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        subprocess.run(["git", "init", "-q", str(self.root)], check=True)
        self.write(".github/repository-hygiene-allowlist.tsv", HEADER.encode())
        self.track(".github/repository-hygiene-allowlist.tsv")

    def close(self) -> None:
        self.temporary.cleanup()

    def write(self, name: str, contents: bytes, executable: bool = False) -> Path:
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(contents)
        if executable:
            path.chmod(path.stat().st_mode | 0o111)
        return path

    def track(self, *names: str) -> None:
        subprocess.run(["git", "-C", str(self.root), "add", "-f", "--", *names], check=True)

    def run(self) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["python3", str(CHECKER), "--root", str(self.root)],
            check=False,
            capture_output=True,
            text=True,
        )


class RepositoryHygieneTests(unittest.TestCase):
    def setUp(self) -> None:
        self.repo = HygieneRepository()

    def tearDown(self) -> None:
        self.repo.close()

    def test_rejects_tracked_mach_o_elf_and_pe(self) -> None:
        pe = bytearray(8_256)
        pe[:2] = b"MZ"
        struct.pack_into("<I", pe, 0x3C, 8_192)
        pe[8_192:8_196] = b"PE\0\0"
        self.repo.write("tmp/mach-o", bytes.fromhex("feedfacf") + bytes(32))
        self.repo.write("tmp/elf", b"\x7fELF" + bytes(32))
        self.repo.write("tmp/windows", bytes(pe))
        self.repo.track("tmp/mach-o", "tmp/elf", "tmp/windows")

        result = self.repo.run()

        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("Mach-O magic", result.stderr)
        self.assertIn("ELF magic", result.stderr)
        self.assertIn("PE magic", result.stderr)

    def test_rejects_tracked_transient_artifacts(self) -> None:
        self.repo.write("src/lib.rs.bak", b"temporary source")
        self.repo.write("debug/session.log", b"temporary log")
        self.repo.write("debug/process.crash", b"temporary crash report")
        self.repo.write("debug/process.ips", b"temporary incident report")
        self.repo.write("target/cache-record", b"temporary build cache")
        self.repo.track(
            "src/lib.rs.bak",
            "debug/session.log",
            "debug/process.crash",
            "debug/process.ips",
            "target/cache-record",
        )

        result = self.repo.run()

        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("src/lib.rs.bak", result.stderr)
        self.assertIn("debug/session.log", result.stderr)
        self.assertIn("debug/process.crash", result.stderr)
        self.assertIn("debug/process.ips", result.stderr)
        self.assertIn("target/cache-record", result.stderr)

    def test_accepts_executable_text_script(self) -> None:
        self.repo.write("scripts/example.sh", b"#!/bin/sh\nprintf '%s\\n' ok\n", executable=True)
        self.repo.write("src/target/mod.rs", b"pub const LABEL: &str = \"source\";\n")
        self.repo.track("scripts/example.sh", "src/target/mod.rs")

        result = self.repo.run()

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_accepts_documented_allowlisted_binary_fixture(self) -> None:
        contents = bytes.fromhex("feedfacf") + bytes(32)
        fixture = self.repo.write("tests/fixtures/arm64-header.bin", contents)
        digest = hashlib.sha256(contents).hexdigest()
        reason = "prebuilt bytes required at parser boundary"
        provenance = (
            "# arm64 header fixture\n\n"
            f"Path: tests/fixtures/arm64-header.bin\n\nSHA-256: {digest}\n\n"
            f"Size: {fixture.stat().st_size}\n\nPlatform: macOS arm64\n\n"
            f"License: CC0-1.0\n\nReason: {reason}\n\n"
            "Origin: generated by scripts/test_repository_hygiene.py\n\n"
            "Regeneration: run python3 scripts/test_repository_hygiene.py\n"
        )
        self.repo.write("tests/fixtures/arm64-header.md", provenance.encode())
        row = (
            f"tests/fixtures/arm64-header.bin\t{digest}\t{fixture.stat().st_size}\t"
            f"macOS arm64\tCC0-1.0\ttests/fixtures/arm64-header.md\t{reason}\n"
        )
        self.repo.write(
            ".github/repository-hygiene-allowlist.tsv", (HEADER + row).encode()
        )
        self.repo.track(
            ".github/repository-hygiene-allowlist.tsv",
            "tests/fixtures/arm64-header.bin",
            "tests/fixtures/arm64-header.md",
        )

        result = self.repo.run()

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_rejects_allowlist_without_complete_provenance(self) -> None:
        contents = bytes.fromhex("feedfacf") + bytes(32)
        fixture = self.repo.write("tests/fixtures/undocumented.bin", contents)
        digest = hashlib.sha256(contents).hexdigest()
        row = f"tests/fixtures/undocumented.bin\t{digest}\t{fixture.stat().st_size}\tmacOS\n"
        self.repo.write(
            ".github/repository-hygiene-allowlist.tsv", (HEADER + row).encode()
        )
        self.repo.track(
            ".github/repository-hygiene-allowlist.tsv", "tests/fixtures/undocumented.bin"
        )

        result = self.repo.run()

        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("every provenance field is required", result.stderr)

    def test_rejects_provenance_without_origin_or_acquisition(self) -> None:
        contents = bytes.fromhex("feedfacf") + bytes(32)
        fixture = self.repo.write("tests/fixtures/untraceable.bin", contents)
        digest = hashlib.sha256(contents).hexdigest()
        reason = "prebuilt bytes required at parser boundary"
        provenance = (
            "# Untraceable fixture\n\n"
            f"tests/fixtures/untraceable.bin\n\n{digest}\n\n{fixture.stat().st_size}\n\n"
            f"macOS arm64\n\nCC0-1.0\n\n{reason}\n"
        )
        self.repo.write("tests/fixtures/untraceable.md", provenance.encode())
        row = (
            f"tests/fixtures/untraceable.bin\t{digest}\t{fixture.stat().st_size}\t"
            f"macOS arm64\tCC0-1.0\ttests/fixtures/untraceable.md\t{reason}\n"
        )
        self.repo.write(
            ".github/repository-hygiene-allowlist.tsv", (HEADER + row).encode()
        )
        self.repo.track(
            ".github/repository-hygiene-allowlist.tsv",
            "tests/fixtures/untraceable.bin",
            "tests/fixtures/untraceable.md",
        )

        result = self.repo.run()

        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("needs a specific Origin", result.stderr)
        self.assertIn("needs a specific Acquisition or Regeneration", result.stderr)


class CurrentTreeHygieneTests(unittest.TestCase):
    def test_current_tracked_tree_passes(self) -> None:
        result = subprocess.run(
            ["python3", str(CHECKER), "--root", str(ROOT)],
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main()
