// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

/**
 * One node of the serializable UI manifest: an element type (the registry
 * key the JSX side maps to a component), a derived stable id, JSON-valued
 * props, and children. This is the wire format for Tauri (#808 attach).
 */
export type DynamicUiNode = { element_type: string, id: string, 
/**
 * JSON-valued props (never pre-rendered strings): a GUI component reads
 * the semantics and decides its own presentation. `BTreeMap` keeps the
 * serialized key order stable so golden JSON and diffs are deterministic.
 */
props: { [key in string]: JsonValue }, children: Array<DynamicUiNode>, };
