// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestColor } from "./ManifestColor";

/**
 * One styled text segment on the wire — the manifest's own shape for a
 * [`Span`], deliberately decoupled from the vocabulary crate so the wire
 * contract carries no Rust dependency. Colours mirror [`SpanColor`]:
 * `indexed` is the xterm 0–15 slot, `rgb` a truecolour triple.
 */
export type ManifestSpan = { text: string, fg: ManifestColor | null, bg: ManifestColor | null, bold: boolean, dim: boolean, };
