// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The manifest's colour shape.
 */
export type ManifestColor = { "Indexed": number } | { "Rgb": [number, number, number] };
