// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicUiNode } from "./DynamicUiNode";

/**
 * The versioned envelope: what crosses the wire. Consumers check
 * `manifest_version` before reading `root`.
 */
export type UiManifest = { manifest_version: number, root: DynamicUiNode, };
